# Generated by Django 4.0.5 on 2022-12-13 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rise_time', models.IntegerField()),
                ('decay_time', models.IntegerField()),
                ('time_of_occurence', models.IntegerField()),
                ('type_of_burst', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='XRayDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50)),
                ('dateUploaded', models.DateField(default=datetime.date.today)),
                ('bursts', models.ManyToManyField(to='burst_finder.burstmodel')),
            ],
        ),
    ]
